[env:cyd-ble]
platform = espressif32@6.9.0
board = esp32dev
board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulstoffregen/XPT2046_Touchscreen@^1.4
    bblanchon/ArduinoJson@^6.21.5
    sudobreakstuff/HijelHID_BLEKeyboard@^1.0.0
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

[env:cyd-wired]
platform = espressif32@6.9.0
board = esp32dev
board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    paulstoffregen/XPT2046_Touchscreen@^1.4
    bblanchon/ArduinoJson@^6.21.5
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
src_filter = +<firmware-wired.ino> +<hid_proto.h>
